// <auto-generated />
namespace TC.BCP.CredinetWeb.Core.Data.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingNamePatientTableRecoverCases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingNamePatientTableRecoverCases));
        
        string IMigrationMetadata.Id
        {
            get { return "202008080404544_AddingNamePatientTableRecoverCases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
