// <auto-generated />
namespace SBTC.Functions.Patients.DataMigrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingQuestionsFormDiagnosis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingQuestionsFormDiagnosis));
        
        string IMigrationMetadata.Id
        {
            get { return "202006030349039_AddingQuestionsFormDiagnosis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
